customhost = "database-1.cc7t5paqsavh.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "tanjacqueline-employee"
customregion = "us-east-1"
